import { useMemo, useState } from 'react'
import { Activity, BarChart3, BookOpenCheck, Download, FileText, GitCompare, Layers3, Network, UsersRound } from 'lucide-react'
import { Badge, Button, EmptyState } from '../components/ui'
import { downloadBlob, formatDate, initials } from '../lib/utils'
import { buildBipartiteNetwork, buildQuestionNetwork, buildStudentNetwork, buildTemporalAnalysis, questionCategory, summarizeBehavior } from '../lib/networkAnalysis'

const colors = ['#47776a', '#b98558', '#796e91', '#56758d', '#a56565', '#748b5f']
const number = (value, digits = 3) => Number(value || 0).toFixed(digits).replace('.', ',')
const percent = (value, digits = 1) => `${(Number(value || 0) * 100).toFixed(digits).replace('.', ',')}%`
const csvCell = (value) => `"${String(value ?? '').replaceAll('"', '""')}"`

function positionedNodes(nodes, bipartite = false) {
  if (bipartite) {
    const groups = { student: nodes.filter((node) => node.type === 'student'), question: nodes.filter((node) => node.type === 'question') }
    return nodes.map((node) => ({ ...node, x: node.type === 'student' ? 24 : 76, y: 7 + (groups[node.type].indexOf(node) + 1) * 86 / (groups[node.type].length + 1) }))
  }
  const communities = [...new Set(nodes.map((node) => node.community))]
  return nodes.map((node) => {
    const group = nodes.filter((item) => item.community === node.community); const groupIndex = communities.indexOf(node.community); const angle = Math.PI * 2 * groupIndex / Math.max(1, communities.length); const inner = Math.PI * 2 * group.indexOf(node) / Math.max(1, group.length)
    const radius = communities.length > 1 ? 27 : 0
    return { ...node, x: 50 + Math.cos(angle) * radius + Math.cos(inner) * Math.min(14, 4 + group.length), y: 50 + Math.sin(angle) * radius + Math.sin(inner) * Math.min(14, 4 + group.length) }
  })
}

function NetworkChart({ network, kind, maxEdges = 700 }) {
  const nodes = positionedNodes(network.nodes, kind === 'bipartite'); const byId = new Map(nodes.map((node) => [node.id, node])); const edges = [...network.edges].sort((a, b) => b.weight - a.weight).slice(0, maxEdges)
  return <div className={`research-network ${kind}`}><svg viewBox="0 0 100 100" role="img" aria-label={`Rede ${kind}`}><g>{edges.map((edge, index) => { const source = byId.get(edge.source); const target = byId.get(edge.target); return source && target ? <line key={`${edge.source}-${edge.target}-${index}`} x1={source.x} y1={source.y} x2={target.x} y2={target.y} opacity={kind === 'bipartite' ? .12 : .18 + edge.weight * .5} stroke={edge.correlation < 0 ? '#b9675f' : '#719589'} strokeWidth={kind === 'bipartite' ? .18 : .25 + edge.weight}><title>{source.label} ↔ {target.label}</title></line> : null })}</g><g>{nodes.map((node) => { const fill = kind === 'bipartite' ? node.type === 'student' ? '#52718a' : '#b98558' : colors[node.community % colors.length]; const radius = kind === 'bipartite' ? 1.35 : 1.8 + (node.centrality?.degree || 0) * 3; return <g key={node.id}><circle cx={node.x} cy={node.y} r={radius} fill={fill} stroke="white" strokeWidth=".45"><title>{node.label}{node.category ? ` · ${node.category}` : ''}</title></circle>{nodes.length <= 45 && <text x={node.x} y={node.y + .45} textAnchor="middle">{kind === 'student' ? initials(node.label) : node.label}</text>}</g> })}</g></svg>{network.edges.length > maxEdges && <small>Exibindo as {maxEdges} ligações de maior peso.</small>}</div>
}

function Metrics({ students, questions }) {
  const ranking = [...students.nodes].sort((a, b) => b.centrality.degree - a.centrality.degree)
  return <><div className="research-metrics"><div><span>Densidade dos alunos</span><strong>{number(students.density)}</strong><small>ligações observadas / possíveis</small></div><div><span>Modularidade</span><strong>{number(students.modularity)}</strong><small>separação das comunidades</small></div><div><span>Comunidades</span><strong>{students.communityCount}</strong><small>propagação de rótulos</small></div><div><span>Densidade dos itens</span><strong>{number(questions.density)}</strong><small>relações acima do limiar</small></div></div><div className="table-wrap"><table className="research-table"><thead><tr><th>ALUNO</th><th>GRUPO</th><th>GRAU</th><th>INTERMEDIAÇÃO</th><th>PROXIMIDADE</th><th>AUTOVETOR</th></tr></thead><tbody>{ranking.slice(0, 12).map((node) => <tr key={node.id}><td><strong>{node.label}</strong></td><td>Comunidade {node.community + 1}</td><td>{number(node.centrality.degree)}</td><td>{number(node.centrality.betweenness)}</td><td>{number(node.centrality.closeness)}</td><td>{number(node.centrality.eigenvector)}</td></tr>)}</tbody></table></div></>
}

function Timeline({ rows }) {
  if (rows.length < 2) return <div className="research-empty"><Activity size={25} /><div><strong>Série temporal insuficiente</strong><p>São necessários ao menos dois simulados corrigidos para a turma selecionada.</p></div></div>
  return <div className="timeline-list">{rows.map((row, index) => <div key={row.assessmentId}><span>{formatDate(row.date)}</span><strong>{row.title}</strong><small>{row.students} alunos · média {row.meanScore.toFixed(1)}% · densidade {number(row.density)} · modularidade {number(row.modularity)} · {row.communities} comunidades</small>{index > 0 && <b className={row.meanScore >= rows[index - 1].meanScore ? 'up' : 'down'}>{row.meanScore >= rows[index - 1].meanScore ? '+' : ''}{(row.meanScore - rows[index - 1].meanScore).toFixed(1).replace('.', ',')} p.p.</b>}</div>)}</div>
}

export function CorrelationPage({ data, notify }) {
  const assessments = data.assessments.filter((item) => data.submissions.some((row) => row.assessmentId === item.id && Array.isArray(row.answers)))
  const [assessmentId, setAssessmentId] = useState(assessments[0]?.id || ''); const [classId, setClassId] = useState('all'); const [dimension, setDimension] = useState('area'); const [category, setCategory] = useState('all'); const [threshold, setThreshold] = useState(.65); const [confidence, setConfidence] = useState(.95); const [view, setView] = useState('overview')
  const assessment = assessments.find((item) => item.id === assessmentId) || assessments[0]
  const categories = useMemo(() => assessment ? [...new Set(Array.from({ length: assessment.questionCount }, (_, index) => questionCategory(assessment, index, dimension)))] : [], [assessment, dimension])
  const studentNetwork = useMemo(() => assessment && buildStudentNetwork({ assessment, submissions: data.submissions, students: data.students, classId, dimension, category, threshold }), [assessment, data.submissions, data.students, classId, dimension, category, threshold])
  const questionNetwork = useMemo(() => assessment && buildQuestionNetwork({ assessment, submissions: data.submissions, classId, dimension, category, confidence }), [assessment, data.submissions, classId, dimension, category, confidence])
  const bipartite = useMemo(() => assessment && buildBipartiteNetwork({ assessment, submissions: data.submissions, students: data.students, classId, dimension, category }), [assessment, data.submissions, data.students, classId, dimension, category])
  const timeline = useMemo(() => buildTemporalAnalysis({ assessments, submissions: data.submissions, students: data.students, classId, threshold }), [assessments, data.submissions, data.students, classId, threshold])
  const selectedSubmissions = useMemo(() => data.submissions.filter((row) => row.assessmentId === assessment?.id && (classId === 'all' || row.classId === classId)), [data.submissions, assessment?.id, classId]); const behavior = useMemo(() => summarizeBehavior(selectedSubmissions), [selectedSubmissions])
  if (!assessment) return <EmptyState icon={GitCompare} title="Ainda não há dados para correlacionar" description="Corrija folhas em pelo menos um simulado para executar as análises de rede." />
  const significant = questionNetwork.edges.filter((edge) => edge.significant); const leader = [...studentNetwork.nodes].sort((a, b) => b.centrality.degree - a.centrality.degree)[0]
  const conclusions = [`A rede apresenta densidade ${number(studentNetwork.density)}, modularidade ${number(studentNetwork.modularity)} e ${studentNetwork.communityCount} comunidade(s).`, leader ? `${leader.label} tem a maior centralidade de grau (${number(leader.centrality.degree)}), indicando maior inserção no padrão compartilhado de respostas.` : 'Não há centralidade estimável no recorte atual.', `${significant.length} de ${questionNetwork.edges.length} associações entre questões são significativas com confiança de ${(confidence * 100).toFixed(0)}%.`, `As folhas reais apresentam ${percent(behavior.blankRate)} de brancos, ${percent(behavior.multipleRate)} de marcações múltiplas e ${percent(behavior.reviewRate)} encaminhadas para revisão.`, 'Os resultados são associativos, não causais; triangule-os com observação docente, mapa de sala e registro das intervenções.']
  function exportCsv() { const rows = [['tipo', 'origem', 'destino', 'peso', 'correlacao', 'p_valor', 'ic_inferior', 'ic_superior', 'n'], ...studentNetwork.edges.map((edge) => ['aluno-aluno', edge.source, edge.target, edge.weight, '', '', '', '', edge.observations]), ...questionNetwork.edges.map((edge) => ['questao-questao', edge.source, edge.target, edge.weight, edge.correlation, edge.p, edge.ci[0], edge.ci[1], edge.n])]; downloadBlob(new Blob([`\ufeff${rows.map((row) => row.map(csvCell).join(';')).join('\n')}`], { type: 'text/csv;charset=utf-8' }), `rede-${assessment.code || assessment.id}.csv`); notify?.('Dados e métricas exportados em CSV.') }
  function exportReport() { const report = { generatedAt: new Date().toISOString(), assessment: { id: assessment.id, title: assessment.title, date: assessment.date }, filters: { classId, dimension, category, threshold, confidence }, sample: { students: studentNetwork.nodes.length, sheets: behavior.sheets }, metrics: { student: { density: studentNetwork.density, modularity: studentNetwork.modularity, communities: studentNetwork.communityCount }, question: { density: questionNetwork.density, modularity: questionNetwork.modularity, communities: questionNetwork.communityCount, significant: significant.length }, behavior, timeline }, nodes: { students: studentNetwork.nodes.map(({ submission, ...node }) => node), questions: questionNetwork.nodes }, edges: { students: studentNetwork.edges, questions: questionNetwork.edges }, conclusions, method: 'Similaridade por concordância; comunidades por propagação de rótulos; centralidades normalizadas; correlação phi/Pearson, p bilateral aproximado e IC por z de Fisher. Análise exploratória, sem inferência causal.' }; downloadBlob(new Blob([JSON.stringify(report, null, 2)], { type: 'application/json' }), `relatorio-${assessment.code || assessment.id}.json`); notify?.('Relatório completo exportado em JSON.') }
  const classes = assessment.classIds?.map((id) => data.classes.find((item) => item.id === id)).filter(Boolean) || []
  const tabs = [['overview', BarChart3, 'Visão geral'], ['students', UsersRound, 'Aluno–aluno'], ['bipartite', Network, 'Aluno–questão'], ['questions', BookOpenCheck, 'Questão–questão'], ['layers', Layers3, 'Multicamada'], ['temporal', Activity, 'Temporal']]
  return <div className="page-stack research-page"><section className="correlation-intro"><span><Network size={21} /></span><div><strong>Análise de redes para pesquisa educacional</strong><p>Comunidades, centralidades, redes multicamada, inferência estatística e evolução temporal calculadas sobre folhas corrigidas.</p></div><Badge tone="blue">{studentNetwork.nodes.length} alunos · {behavior.sheets} folhas reais</Badge></section>
    <section className="panel research-toolbar"><div className="research-filter-grid"><label><span>Simulado</span><select value={assessment.id} onChange={(event) => { setAssessmentId(event.target.value); setClassId('all'); setCategory('all') }}>{assessments.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label><span>Turma</span><select value={classId} onChange={(event) => setClassId(event.target.value)}><option value="all">Todas</option>{classes.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label><span>Comparar por</span><select value={dimension} onChange={(event) => { setDimension(event.target.value); setCategory('all') }}><option value="area">Área</option><option value="skill">Habilidade</option><option value="descriptor">Descritor</option><option value="content">Conteúdo</option></select></label><label><span>Recorte</span><select value={category} onChange={(event) => setCategory(event.target.value)}><option value="all">Todos</option>{categories.map((item) => <option key={item}>{item}</option>)}</select></label><label><span>Similaridade {percent(threshold, 0)}</span><input type="range" min=".4" max=".95" step=".05" value={threshold} onChange={(event) => setThreshold(Number(event.target.value))} /></label><label><span>Confiança</span><select value={confidence} onChange={(event) => setConfidence(Number(event.target.value))}><option value=".9">90%</option><option value=".95">95%</option><option value=".99">99%</option></select></label></div><div className="research-actions"><Button variant="secondary" onClick={exportCsv}><Download size={15} />CSV</Button><Button onClick={exportReport}><FileText size={15} />Relatório completo</Button></div></section>
    <nav className="research-tabs">{tabs.map(([id, Icon, label]) => <button key={id} className={view === id ? 'active' : ''} onClick={() => setView(id)}><Icon size={15} />{label}</button>)}</nav>
    {view === 'overview' && <><section className="panel"><header className="panel-header"><div><h3>Métricas estruturais e centralidade</h3><p>Indicadores normalizados para comparação entre recortes.</p></div><Badge tone="neutral">n = {studentNetwork.nodes.length}</Badge></header><Metrics students={studentNetwork} questions={questionNetwork} /></section><section className="panel research-report"><header className="panel-header"><div><h3>Conclusões pedagógicas automáticas</h3><p>Síntese para revisão do pesquisador.</p></div><Badge tone="ochre">Exploratória</Badge></header><ol>{conclusions.map((item) => <li key={item}>{item}</li>)}</ol></section></>}
    {view === 'students' && <section className="panel"><header className="panel-header"><div><h3>Comunidades de alunos</h3><p>Cores representam comunidades; tamanho reflete centralidade de grau.</p></div><Badge tone="blue">{studentNetwork.communityCount} comunidades</Badge></header><NetworkChart network={studentNetwork} kind="student" /></section>}
    {view === 'bipartite' && <section className="panel"><header className="panel-header"><div><h3>Rede aluno–questão</h3><p>Azul: alunos; ocre: questões; arestas: marcações observadas.</p></div><Badge tone="neutral">Densidade {number(bipartite.density)}</Badge></header><NetworkChart network={bipartite} kind="bipartite" /></section>}
    {view === 'questions' && <section className="panel"><header className="panel-header"><div><h3>Rede questão–questão</h3><p>Correlação phi, significância bilateral e intervalo de confiança por z de Fisher.</p></div><Badge tone="blue">{significant.length} significativas</Badge></header><NetworkChart network={questionNetwork} kind="question" /><div className="table-wrap"><table className="research-table"><thead><tr><th>PAR</th><th>φ</th><th>IC</th><th>p</th><th>n</th><th>RESULTADO</th></tr></thead><tbody>{questionNetwork.edges.slice().sort((a, b) => a.p - b.p).slice(0, 20).map((edge) => <tr key={`${edge.source}-${edge.target}`}><td>{edge.source.toUpperCase()} × {edge.target.toUpperCase()}</td><td>{number(edge.correlation)}</td><td>[{number(edge.ci[0])}; {number(edge.ci[1])}]</td><td>{edge.p < .001 ? '< 0,001' : number(edge.p)}</td><td>{edge.n}</td><td><Badge tone={edge.significant ? 'green' : 'neutral'}>{edge.significant ? 'Significativa' : 'Não significativa'}</Badge></td></tr>)}</tbody></table></div></section>}
    {view === 'layers' && <section className="panel"><header className="panel-header"><div><h3>Rede multicamada integrada</h3><p>Integra camadas social-cognitiva, de itens e de participação.</p></div><Badge tone="blue">3 camadas</Badge></header><div className="multilayer-grid">{[[studentNetwork, 'student', 'Aluno–aluno'], [questionNetwork, 'question', 'Questão–questão'], [bipartite, 'bipartite', 'Aluno–questão']].map(([network, kind, label]) => <div key={kind}><NetworkChart network={network} kind={kind} maxEdges={300} /><strong>{label}</strong><small>{network.nodes.length} nós · {network.edges.length} arestas</small></div>)}</div></section>}
    {view === 'temporal' && <><section className="panel"><header className="panel-header"><div><h3>Mudanças após intervenções</h3><p>Série longitudinal por aplicação; não atribui causalidade sem desenho pré/pós.</p></div><Badge tone="neutral">{timeline.length} momentos</Badge></header><Timeline rows={timeline} /></section><section className="panel"><header className="panel-header"><div><h3>Comportamento real em sala</h3><p>Indicadores observados nas folhas e na leitura óptica.</p></div></header><div className="research-metrics"><div><span>Folhas</span><strong>{behavior.sheets}</strong><small>registros processados</small></div><div><span>Em branco</span><strong>{percent(behavior.blankRate)}</strong><small>{behavior.totalAnswers} respostas</small></div><div><span>Múltiplas</span><strong>{percent(behavior.multipleRate)}</strong><small>dúvida ou rasura</small></div><div><span>Confiança OMR</span><strong>{behavior.meanConfidence === null ? '—' : `${behavior.meanConfidence.toFixed(1)}%`}</strong><small>{percent(behavior.reviewRate)} para revisão</small></div></div><p className="method-note">Posição em sala e interação oral não são inferidas. Para publicação, combine com diário de campo, mapa de sala e protocolo de intervenção.</p></section></>}
  </div>
}
